version: 2
jobs:
  build:
    working_directory: /go/src/github.com/guregu/dynamo
    parallelism: 1
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout

      - run:
          name: Print env
          command: |
            go env
            go version
      - run:
          name: go get
          command: go get

      - run:
          name: go build
          command: go build

      - run:
          name: go test
          command: go test